language: ruby
bundler_args: --without production
services: 
  - postgresql
before_script:
  - psql -c 'create database lancaster_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec


